site_name: My skill
site_description: My skill
site_author: raisack
# TODO: 追々公開する必要？
site_url: https://raisack8.github.io/my-skill/
repo_name: raisack8/my-skill
repo_url: https://github.com/raisack8/my-skill
copyright: Copyright &copy 2024 raisack

theme:
  name: material
  palette:
    # ライトモード
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: ダークモードに切り替え
    # ダークモード
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: ライトモードに切り替え

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - meta

nav:
  - ホーム: index.md
  - Python: 
    - FastAPI: python/py-fastapi-01.md
    - Django: python/py-django-01.md
    - pytest(準備中): python/py-pytest-01.md
    - subprocess(準備中): python/py-subpro-01.md
    - pathlib(準備中): python/py-pathlib-01.md
    - mkdocs(準備中): python/py-mkdocs-01.md
  - React(準備中):
    - セットアップ: react/re-first-01.md
    - Hooks: react/re-hooks-01.md
  - bat(準備中): bat-01.md
  - PostgreSQL(準備中): psql-01.md
  - AWS(準備中): aws-first-01.md
  - GCP(準備中): gcp-first-01.md
  - Stable Diffusion(準備中):
    - 基本的な使い方: stablediffusion/sd-first-01.md
    - プロンプト: stablediffusion/sd-prompt-01.md
  - ハック(準備中):
    - VSCODE: hack-vscode-01.md
  - ネットワーク: network/network.md