site_name: My skill
site_description: My skill
site_author: raisack
site_url: https://raisack8.github.io/my-skill/
repo_name: raisack8/my-skill
repo_url: https://github.com/raisack8/my-skill
copyright: Copyright &copy 2024 raisack

theme:
  name: material
  custom_dir: "theme/"
  palette:
    # ライトモード
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: ダークモードに切り替え
    # ダークモード
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: ライトモードに切り替え
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - meta

nav:
  - ホーム: index.md
  - TypeScript:
    - javascriptの歴史: ts/history.md
    - Next.js:
      - はじめに: ts/nextjs/ne-first.md
      - チュートリアル: 
        - 特徴: ts/nextjs/ne-about.md
        - レイアウトとページ: ts/nextjs/ne-pages.md
        - DBの設定(Vercel): ts/nextjs/ne-db.md
        - レンダリング: ts/nextjs/ne-render.md
        - 検索: ts/nextjs/ne-search.md
        - エラーハンドリング: ts/nextjs/ne-error.md
        - 認証: ts/nextjs/ne-auth.md
        - 環境構築: ts/nextjs/ne-env.md
        - Vercel: ts/nextjs/ne-vercle.md
      - 実践:
        - NextUI: ts/nextjs/practice/ne-01.md
        - こんなときどうする: ts/nextjs/practice/ne-02.md
    - ORM:
      - Prisma:
        - 使い方: ts/orm/prisma/pr-01.md
      - Drizzle:
        - クイックスタート: ts/orm/drizzle/dr-01.md
    - Store:
      - Redux:
        - クイックスタート: ts/store/redux/rd-01.md
  - Python: 
    - FastAPI: python/py-fastapi-01.md
    - Django: python/py-django-01.md
    - Selenium: python/py-sele.md
    # - pytest(準備中): python/py-pytest-01.md
    # - subprocess(準備中): python/py-subpro-01.md
    # - pathlib(準備中): python/py-pathlib-01.md
    # - mkdocs(準備中): python/py-mkdocs-01.md
  - Docker: 
    - はじめに: docker/dc-01.md
    - Dockerfile: docker/dc-02.md
  - GCP: gcp/gcp-first-01.md
  - Figma: 
    - 使い方: fg/fg-01.md
    - コンポーネント: fg/fg-02.md

  # - bat(準備中): bat-01.md
  # - PostgreSQL(準備中): psql-01.md
  # - AWS(準備中): aws-first-01.md
  # - Stable Diffusion(準備中):
  #   - 基本的な使い方: stablediffusion/sd-first-01.md
  #   - プロンプト: stablediffusion/sd-prompt-01.md
  # - ハック(準備中):
  #   - VSCODE: hack-vscode-01.md
  - ネットワーク: network/network.md
  - 良記事: books.md
